# This file was generated by GoReleaser. DO NOT EDIT.
cask "koc" do
  # Homebrew >= 6.0.13 takes the declarative steps; older clients keep the
  # `postflight` block, which is only deprecated from 6.0.16 on.
  steps_dsl = defined?(Homebrew::InstallSteps::DSL) && Homebrew::InstallSteps::DSL
  if steps_dsl && steps_dsl.method_defined?(:run) && steps_dsl.method_defined?(:on_macos)
    postflight_steps do
      on_macos do
        run "/usr/bin/xattr",
            args: ["-dr", "com.apple.quarantine", "{{staged_path}}/koc"]
      end
    end
  else
    postflight do
      if OS.mac?
        system_command "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "#{staged_path}/koc"]
      end
    end
  end

  version "0.33.0"

  on_macos do
    on_arm do
      sha256 "fb5a5b24ac8dc5b9af95315a7b0d2a722b594ddad09329483ff27ce4af6a145a"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b212e9726d6feffa6976590c949a1635b50a8aa82f71caf2ffe76b6793e73988"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f825cbc0f448547fd75e8b02f71b2586af0c6d3856f13db98ac60a4936763815"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e6357b14942f1871227cc678eb28b3eaab9fc5d78781cfe84dbe85061ae0d387"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_linux_amd64.tar.gz"
    end
  end

  name "koc"
  desc "Single-binary OpenStack CLI for KeyStack (gophercloud v2)"
  homepage "https://github.com/ftarasenko/go-openstackclient"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "koc"

  # No zap stanza required
end
