# This file was generated by GoReleaser. DO NOT EDIT.
cask "koc" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "bcd5cd15bb2faba38534d8c93397310f2713150acbcaf3aa03c15f439cc06713"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "df47dfd92da9ced7007b070e3368bdac1893fd669d2640921b5d946e44572ad0"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a9dad08862e4834985ca0ab0d7138dce63265f4186f0132b1c77a371042da031"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a71e6dbd72ba12435510817c82360634e6e1c4020ae62b35efdfe8d843dfd87e"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "koc"
  desc "Single-binary OpenStack CLI for KeyStack (gophercloud v2)"
  homepage "https://github.com/ftarasenko/go-openstackclient"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "koc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/koc"]
    end
  end

  # No zap stanza required

end
