# This file was generated by GoReleaser. DO NOT EDIT.
cask "koc" do
  version "0.14.0"

  on_macos do
    on_intel do
      sha256 "a7d45209c9e253ed0e9308b262074ba835fece05ae3e1cb90e7ef785b6472f3d"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bf2d69ff7bda8d3d817c1430004667eb1ce1ac528f2078e1268994f9ddecfdbf"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c9c3c437041e05ae9ba9331f061ebf167cb4de1de697a51d260de281d83b523f"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5da1effd43226dc442c816e65a3bf0adb340f0ff761718e8688cb302f0897241"
      url "https://github.com/ftarasenko/go-openstackclient/releases/download/v#{version}/koc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "koc"
  desc "Single-binary OpenStack CLI for KeyStack (gophercloud v2)"
  homepage "https://github.com/ftarasenko/go-openstackclient"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "koc"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/koc"]
    end
  end

  # No zap stanza required

end
